src/FlowGuardMonitoring.WebHost/Controllers/NotificationsController.cs
using FlowGuardMonitoring.BLL.Contracts;
using FlowGuardMonitoring.DAL.Models;
using FlowGuardMonitoring.DAL.Repositories;
using FlowGuardMonitoring.WebHost.Models.Notifications;
using FlowGuardMonitoring.WebHost.Models.Tables;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FlowGuardMonitoring.WebHost.Controllers;

[Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
public class NotificationsController : Controller
{
    private readonly NotificationRepository notificationRepository;
    private readonly IPaginationService<Notification> notificationPagination;
    private readonly ICurrentUser currentUser;

    public NotificationsController(
        NotificationRepository notificationRepository,
        ICurrentUser currentUser,
        IPaginationService<Notification> notificationPagination)
    {
        this.notificationRepository = notificationRepository;
        this.currentUser = currentUser;
        this.notificationPagination = notificationPagination;
    }

    public async Task<IActionResult> Index(string searchValue = "")
    {
        var notifications = await this.notificationRepository.GetPagedAsync(
            1,
            int.MaxValue,
            "NotificationId",
            "asc",
            searchValue,
            this.currentUser.UserId);
        return this.View(notifications);
    }

    [HttpPost]
    public async Task<IActionResult> GetNotifications([FromBody] DataTablesRequest request)
    {
        int pageNumber = (request.Start / request.Length) + 1;

        var notifications = await this.notificationPagination.GetPaginatedRecords(
            pageNumber,
            request.Length,
            request.SortColumn,
            request.SortDirection,
            request.SearchValue,
            this.currentUser.UserId);

        var viewModel = notifications.Records.Select(n => new NotificationViewModel
        {
            NotificationId = n.NotificationId,
            Time = n.Date,
            Message = n.Description,
            Type = n.Type,
            IsRead = n.IsRead,
        }).ToList();

        var jsonData = new
        {
            draw = request.Draw,
            recordsFiltered = notifications.TotalRecords,
            recordsTotal = notifications.TotalRecords,
            data = viewModel,
        };

        return this.Ok(jsonData);
    }

    [HttpGet("/api/notifications/recent")]
    public async Task<IActionResult> GetRecentNotifications()
    {
        var notifications = await this.notificationRepository.GetPagedAsync(
            pageNumber: 1,
            pageSize: 4,
            sortColumn: string.Empty,
            sortDirection: "desc",
            searchValue: string.Empty,
            userId: this.currentUser.UserId);

        return this.Json(notifications);
    }

    [HttpPut("/api/notifications/mark-as-read")]
    public async Task<IActionResult> MarkAsRead(int notificationId)
    {
        if (notificationId <= 0 || (await this.notificationRepository.GetByIdAsync(notificationId))?.UserId != this.currentUser.UserId)
        {
            return this.BadRequest();
        }

        await this.notificationRepository.MarkAsRead(notificationId);
        return this.Ok();
    }

    [HttpGet("/api/notifications/count")]
    public async Task<IActionResult> CountUnreadNotifications()
    {
        return this.Json(this.notificationRepository.GetUnreadCount(this.currentUser.UserId));
    }
}

src/FlowGuardMonitoring.WebHost/Controllers/SettingsController.cs
using FlowGuardMonitoring.DAL.Models;
using FlowGuardMonitoring.WebHost.Extentions;
using FlowGuardMonitoring.WebHost.Models.Settings;
using FlowGuardMonitoring.WebHost.Resources;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Configuration;

namespace FlowGuardMonitoring.WebHost.Controllers;

[Route("/settings")]
[Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
public class SettingsController : Controller
{
    private readonly UserManager<User> userManager;

    public SettingsController(UserManager<User> userManager)
    {
        this.userManager = userManager;
    }

    [HttpGet("/account")]
    public async Task<ActionResult> Account()
    {
        if (!this.IsUserAuthenticated())
        {
            this.RedirectToDefault();
        }

        var user = await this.userManager.FindByNameAsync(this.User.Identity?.Name!);
        if (user == null)
        {
            return this.NotFound();
        }

        return this.View(new AccountViewModel()
        {
            EditInfo = false,
            FirstName = user.FirstName,
            LastName = user.LastName,
            EditEmail = false,
            Email = user.Email!,
            EditPassword = false,
            OldPassword = string.Empty,
            NewPassword = string.Empty,
            ConfirmPassword = string.Empty,
        });
    }

    [HttpPost("/account")]
    public async Task<ActionResult> Account(AccountViewModel model)
    {
        if (this.IsUserAuthenticated())
        {
            this.RedirectToDefault();
        }

        if (this.ModelState.IsValid)
        {
            var user = await this.userManager.FindByNameAsync(this.User.Identity?.Name!);
            if (user == null)
            {
                return this.NotFound();
            }

            if (model.EditInfo == true)
            {
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
            }

            if (model.EditEmail == true)
            {
                user.Email = model.Email;
            }

            if (model.EditPassword == true)
            {
                var passwordHasher = new PasswordHasher<User>();
                var passwordVerificationResult =
                    passwordHasher.VerifyHashedPassword(user, user.PasswordHash!, model.OldPassword!);

                if (passwordVerificationResult != PasswordVerificationResult.Success)
                {
                    this.ModelState.AddModelError(string.Empty, AuthLocals.ResetPasswordNewPasswordSameAsCurrent);
                    return this.View(model);
                }

                await this.userManager.ChangePasswordAsync(user, model.OldPassword!, model.NewPassword!);
            }
        }

        return this.View(model);
    }

    [HttpGet]
    public async Task<IActionResult> ConfirmEmailChange(string userId, string email, string token)
    {
        var user = await this.userManager.FindByIdAsync(userId);
        if (user == null)
        {
            return this.NotFound();
        }

        var result = await this.userManager.ChangeEmailAsync(user, email, token);
        if (result.Succeeded)
        {
            this.TempData["SuccessMessage"] = "Email changed successfully.";
            return this.RedirectToAction(nameof(this.Account));
        }

        return this.RedirectToAction(nameof(this.Account));
    }
}

src/FlowGuardMonitoring.WebHost/Controllers/TablesController.cs
using FlowGuardMonitoring.BLL.Contracts;
using FlowGuardMonitoring.BLL.Models;
using FlowGuardMonitoring.DAL.Models;
using FlowGuardMonitoring.DAL.Repositories;
using FlowGuardMonitoring.WebHost.Models.Tables;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace FlowGuardMonitoring.WebHost.Controllers;

[Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
public class TablesController : Controller
{
    private readonly IPaginationService<Sensor> sensorPagination;
    private readonly IPaginationService<Site> sitesPagination;
    private readonly IPaginationService<Measurement> measurementsPagination;
    private readonly ICurrentUser currentUser;
    public TablesController(
        IPaginationService<Sensor> sensorPagination,
        IPaginationService<Site> sitesPagination,
        IPaginationService<Measurement> measurementsPagination,
        ICurrentUser currentUser)
    {
        this.sensorPagination = sensorPagination;
        this.sitesPagination = sitesPagination;
        this.measurementsPagination = measurementsPagination;
        this.currentUser = currentUser;
    }

    public async Task<ActionResult> Sensors()
    {
        return this.View(new PaginatedResult<SensorViewModel>());
    }

    public async Task<ActionResult> Sites()
    {
        return this.View(new PaginatedResult<SiteViewModel>());
    }

    public async Task<ActionResult> Measurements()
    {
        return this.View(new PaginatedResult<MeasurementViewModel>());
    }

    [HttpPost]
    public async Task<IActionResult> GetMeasurements([FromBody] DataTablesRequest request)
    {
        int pageNumber = (request.Start / request.Length) + 1;

        var measurements = await this.measurementsPagination.GetPaginatedRecords(
            pageNumber,
            request.Length,
            request.SortColumn,
            request.SortDirection,
            request.SearchValue,
            this.currentUser.UserId);

        var viewModel = measurements.Records.Select(m => new MeasurementViewModel
        {
            SensorName = m.Sensor.Name,
            Timestamp = m.Timestamp.ToString("dd-MM-yyyy HH:mm"),
            Type = m.Sensor.Type.ToString(),
            Value = m.Value,
        }).ToList();

        var jsonData = new
        {
            draw = request.Draw,
            recordsFiltered = measurements.TotalRecords,
            recordsTotal = measurements.TotalRecords,
            data = viewModel,
        };

        return this.Ok(jsonData);
    }

    [HttpPost]
    public async Task<IActionResult> GetSensors([FromBody] DataTablesRequest request)
    {
        int pageNumber = (request.Start / request.Length) + 1;

        var sensors = await this.sensorPagination.GetPaginatedRecords(
            pageNumber,
            request.Length,
            request.SortColumn,
            request.SortDirection,
            request.SearchValue,
            this.currentUser.UserId);

        var viewModel = sensors.Records.Select(s => new
        {
            Name = s.Name,
            Type = s.Type.ToString(),
            InstallationDate = s.InstallationDate,
            IsActive = s.IsActive,
            SiteName = s.Site.Name,
            SensorId = s.SensorId,
        }).ToList();

        var jsonData = new
        {
            draw = request.Draw,
            recordsFiltered = sensors.TotalRecords,
            recordsTotal = sensors.TotalRecords,
            data = viewModel,
        };

        return this.Ok(jsonData);
    }

    [HttpPost]
    public async Task<IActionResult> GetSites([FromBody] DataTablesRequest request)
    {
        int pageNumber = (request.Start / request.Length) + 1;

        var sites = await this.sitesPagination.GetPaginatedRecords(
            pageNumber,
            request.Length,
            request.SortColumn,
            request.SortDirection,
            request.SearchValue,
            this.currentUser.UserId);

        var viewModel = sites.Records.Select(s => new SiteViewModel
        {
            Name = s.Name,
            Description = s.Description,
            Latitude = s.Latitude,
            Longitude = s.Longitude,
        }).ToList();

        var jsonData = new
        {
            draw = request.Draw,
            recordsFiltered = sites.TotalRecords,
            recordsTotal = sites.TotalRecords,
            data = viewModel,
        };

        return this.Ok(jsonData);
    }
}

src/FlowGuardMonitoring.WebHost/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
        <nav class="pull-left">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="https://ndespotov.com">
                        About Me
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright">
            2025, made with <i class="fa fa-heart heart text-danger"></i> by
            <a href="https://ndespotov.com">Nikolay Despotov</a>
        </div>
        <div>
            <a target="_blank" href="https://github.com/codingburgas/2425-dzi-csharp-NVDespotov20">Github Repo</a>
        </div>
    </div>
</footer>

src/FlowGuardMonitoring.WebHost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewData["Title"] | FlowGuard Monitoring</title>
    <meta
        content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
        name="viewport"
    />
    <link
        rel="icon"
        href="~/favicon.ico"
        type="image/x-icon"
    />

    <!-- Fonts and icons -->
    <script src="~/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { families: ["Public Sans:300,400,500,600,700"] },
            custom: {
                families: [
                    "Font Awesome 6 Solid",
                    "Font Awesome 6 Regular",
                    "Font Awesome 6 Brands",
                    "simple-line-icons",
                ],
                urls: [ "/css/all.min.css"],
            },
            active: function () {
                sessionStorage.fonts = true;
            },
        });
    </script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="~/css/flatpickr.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/plugins.min.css" />
    <link rel="stylesheet" href="~/css/flowguard.min.css" />
    @if (ViewData["Map"] != null)
    {
    <!-- Leaflet CSS -->
    <link 
        rel="stylesheet" 
        href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        crossorigin=""
    />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
    }

</head>
<body>
<div class="wrapper">
    <partial name="_Sidebar"/>
    <div class="main-panel">
        <div class="main-header">
            <div class="main-header-logo">
                <!-- Logo Header -->
                <div class="logo-header" data-background-color="dark">
                    <a asp-page="/Home/Index" class="logo">
                        <img
                            src="~/img/logo.svg"
                            alt="navbar brand"
                            class="navbar-brand"
                            height="20"/>
                    </a>
                    <div class="nav-toggle">
                        <button class="btn btn-toggle toggle-sidebar">
                            <i class="gg-menu-right"></i>
                        </button>
                        <button class="btn btn-toggle sidenav-toggler">
                            <i class="gg-menu-left"></i>
                        </button>
                    </div>
                    <button class="topbar-toggler more">
                        <i class="gg-more-vertical-alt"></i>
                    </button>
                </div>
                <!-- End Logo Header -->
            </div>
            <partial name="_Navbar"/>
        </div>
        <div class="container">
            <div class="page-inner">
                @RenderBody()
            </div>
        </div>
    </div>
</div>
<!--   Core JS Files   -->

<script src="~/js/core/jquery-3.7.1.min.js"></script>
<script src="~/js/core/popper.min.js"></script>
<script src="~/js/core/bootstrap.min.js"></script>

<!-- jQuery Scrollbar -->
<script src="~/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

<!-- Chart.js -->
<script src="~/js/plugin/chart.js/chart.min.js"></script>

<!-- jQuery Sparkline -->
<script src="~/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

<!-- FlatPickr -->
<script src="~/js/plugin/flatpickr/flatpickr.js"></script>

<!-- Day.js -->
<script src="~/js/plugin/day.js/dayjs.min.js"></script>
<script src="~/js/plugin/day.js/relativetime.min.js"></script>
<script>
    dayjs.extend(dayjs_plugin_relativeTime);
</script>

<!-- Datatables -->
<script src="~/js/plugin/datatables/datatables.min.js"></script>

<!-- Bootstrap Notify -->
<script src="~/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

<!-- jQuery Vector Maps -->
<script src="~/js/plugin/jsvectormap/jsvectormap.min.js"></script>
<script src="~/js/plugin/jsvectormap/world.js"></script>

<!-- Sweet Alert -->
<script src="~/js/plugin/sweetalert/sweetalert.min.js"></script>
<script type="text/javascript" src="~/js/plugin/default-passive-events/dist/index.js"></script>

@if (ViewData["Map"] != null)
{
<script
    src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin=""
></script>
<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
}

<!-- FlowGuard JS -->
<script src="~/js/flowguard.js"></script>

<partial name="_LogoutModal"/>
@if ((bool)(ViewData["MeasurementsScript"] ?? false))
{
    <partial name="Measurements/_MeasurementsScript"/>
}
@if (ViewData["ScriptPath"] != null)
{
    if (ViewData["ScriptModel"] != null)
    {
        <partial name="../@ViewData["ScriptPath"]" model="@ViewData["ScriptModel"]"/>
    }
    else
    {
        <partial name="../@ViewData["ScriptPath"]"/>
    }
}
</body>
</html>

src/FlowGuardMonitoring.WebHost/Views/Shared/_LogoutModal.cshtml
@using System.Text.Encodings.Web
<script>
    $("#logout").click(function (e) {
        swal({
            title: "Log out?",
            text: "Are you sure you want to log out?",
            type: "warning",
            buttons: {
                cancel: {
                    visible: true,
                    className: "btn btn-danger",
                },
                confirm: {
                    text: "Yes",
                    className: "btn btn-success",
                },
            },
        }).then((logout) => {
            if (logout) {
                fetch(
                    '/logout',
                    {
                        method: 'post'
                    }
                )
                swal("Logged out successfully!", {
                    buttons: {
                        confirm: {
                            className: "btn btn-success",
                        },
                    },
                }).then(() => {
                    location.reload()
                })
            }
        });
    });
</script>

src/FlowGuardMonitoring.WebHost/Views/Shared/_Navbar.cshtml
@using FlowGuardMonitoring.DAL.Models
@using FlowGuardMonitoring.WebHost.Models.Settings
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager
@{
    var user = User.Identity is { IsAuthenticated: true } ? await UserManager.GetUserAsync(User) : null;
}
<nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
    <div class="container-fluid">
        <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
            <li class="nav-item topbar-icon dropdown hidden-caret">
                <a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-bell"></i>
                    <span class="notification" id="notifCount">4</span>
                </a>
                <ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
                    <li>
                        <div class="dropdown-title" id="notifTitle">
                            You have 0 new notification(s)
                        </div>
                    </li>
                    <li>
                        <div class="notif-scroll" style="max-height: 300px; overflow-y: auto;">
                            <div class="notif-center" id="notifList">
                                <!-- Notifications will be dynamically inserted here -->
                            </div>
                        </div>
                    </li>
                    <li>
                        <a class="see-all" href="@Url.Action("Index", "Notifications")">See all notifications<i class="fa fa-angle-right"></i></a>
                    </li>
                </ul>
            </li>
            <li class="nav-item topbar-user dropdown hidden-caret">
                <a class="profile-pic" href="@Url.Action("Account", "Settings")">
                    <div class="avatar-sm">
                        <img src="~/img/profile.jpg" alt="..." class="avatar-img rounded-circle" />
                    </div>
                    <span class="profile-username">
                        <span class="op-7">Hello, </span>
                        <span class="fw-bold">@(user?.FirstName ?? "User")</span>
                    </span>
                </a>
                <ul class="dropdown-menu dropdown-user animated fadeIn">
                    <div class="dropdown-user-scroll scrollbar-outer">
                        <li>
                            <a class="dropdown-item">Account Setting</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item">Logout</a>
                        </li>
                    </div>
                </ul>
            </li>
            <li class="nav-item topbar-icon dropdown hidden-caret">
                <a class="nav-link" id="logout">
                    <i class="fa fa-right-from-bracket"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

<script>
    // Function to fetch recent notifications
    async function fetchRecentNotifications() {
        try {
            const response = await fetch('/api/notifications/recent');
            const notifications = await response.json();

            const countResponse = await fetch('/api/notifications/count')
            var count = await countResponse.json();
            const notifCount = document.getElementById('notifCount');
            notifCount.textContent = count <= 9 ? count : '9+';

            const notifTitle = document.getElementById('notifTitle');
            notifTitle.textContent = `You have ${count} new notification${count !== 1 ? 's' : ''}`;

            const notifList = document.getElementById('notifList');
            notifList.innerHTML = '';

            notifications.forEach(notification => {
                const notifItem = document.createElement('a');
                notifItem.href = '#';
                notifItem.dataset.notificationId = notification.notificationId;

                let icon = '';
                let badge = '';
                switch (notification.type) {
                    case 'Warning':
                        icon = 'fa-triangle-exclamation';
                        badge = 'warning';
                        break;
                    case 'Critical':
                        icon = 'fa-radiation';
                        badge = 'danger';
                        break;
                    case 'Error':
                        icon = 'fa-xmark';
                        badge = 'danger';
                        break;
                    case 'Info':
                        icon = 'fa-info-circle';
                        badge = 'info';
                        break;
                }

                // Add notification content dynamically
                const notifContent = `
                    <div class="d-flex align-items-center">
                        <div class="badge-${badge} rounded-circle mx-3" style="width: 50px; height: 50px; overflow: hidden; text-align: center;">
                            <i class="fas ${icon} text-white fa-2x" style="line-height: 50px;"></i>
                        </div>
                        <div class="notif-content flex-grow-1" style="max-width: calc(100% - 50px);">
                            <span class="block ${!notification.isRead ? 'strong' : ''}">${notification.title} 
                            ${!notification.isRead ? '<i class="fa-circle fa fa-2xs text-danger new-notification-icon"></i>' : ''}
                            </span>
                            <span class="time">${dayjs(notification.date).fromNow()}</span>
                        </div>
                    </div>
                `;
                notifItem.innerHTML = notifContent;

                notifItem.addEventListener('click', async function(event) {
                    event.preventDefault();
                    event.stopPropagation();

                    const notificationId = this.dataset.notificationId;
                    if (notificationId) {
                        await markNotificationAsRead(notificationId);
                        let notifTextEl = this.querySelector('.notif-content span.block');
                        if (notifTextEl.classList.contains('strong')) {
                            notifTextEl.classList.remove('strong');
                            notifTextEl.textContent = notification.title;
                            notifTextEl.getElementsByClassName("new-notification-icon")[0].remove();
                            notifTitle.textContent = `You have ${--count} new notification${count !== 1 ? 's' : ''}`;
                            notifCount.textContent = count <= 9 ? count : '9+';
                        }
                    }
                });

                notifList.appendChild(notifItem);
            });
        } catch (error) {
            console.error('Error fetching notifications:', error);
        }
    }

    // Function to mark a notification as read
    async function markNotificationAsRead(notificationId) {
        try {
            const response = await fetch(`/api/notifications/mark-as-read?notificationId=${notificationId}`, {
                method: 'PUT'
            });

            if (response.ok) {
                console.log(`Notification ${notificationId} marked as read.`);
            } else {
                console.error('Failed to mark notification as read.');
            }
        } catch (error) {
            console.error('Error marking notification as read:', error);
        }
    }

    document.addEventListener('DOMContentLoaded', function () {
        fetchRecentNotifications();

        setInterval(fetchRecentNotifications, 30000);
    });
</script>

src/FlowGuardMonitoring.WebHost/Views/Shared/_Sidebar.cshtml
<div class="sidebar sidebar-style-2" data-background-color="dark">
  <div class="sidebar-logo">
    <!-- Logo Header -->
    <div class="logo-header" data-background-color="dark">
      <a href="@Url.Action("Index", "Home")" class="logo">
        <img
          src="~/img/logo_long.svg"
          alt="navbar brand"
          class="navbar-brand"
          height="40"
        />
      </a>
      <div class="nav-toggle">
        <button class="btn btn-toggle toggle-sidebar">
          <i class="gg-menu-right"></i>
        </button>
        <button class="btn btn-toggle sidenav-toggler">
          <i class="gg-menu-left"></i>
        </button>
      </div>
      <button class="topbar-toggler more">
        <i class="gg-more-vertical-alt"></i>
      </button>
    </div>
    <!-- End Logo Header -->
  </div>
  <div class="sidebar-wrapper scrollbar scrollbar-inner">
    <div class="sidebar-content">
      <ul class="nav nav-secondary">
        <li class="nav-section">
                <span class="sidebar-mini-icon">
                  <i class="fa fa-ellipsis-h"></i>
                </span>
        </li>
        <li class="nav-item">
          <a href="@Url.Action("Index", "Home")">
            <i class="fa-house fa-solid"></i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="@Url.Action("Sensors", "Tables")">
            <i class="fa-solid fa-gauge"></i>
            <p>Sensors</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="@Url.Action("Sites", "Tables")">
            <i class="fa-solid fa-location-dot"></i>
            <p>Locations</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="@Url.Action("Measurements", "Tables")">
            <i class="fa-solid fa-chart-line"></i>
            <p class="sub-item">Measurements</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="@Url.Action("Index", "Notifications")">
            <i class="fa-solid fa-bell"></i>
            <p class="sub-item">Notifications</p>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>